version: '3.9'

services:
  # PostgreSQL database with production settings
  db:
    image: postgres:16
    container_name: he-postgres
    environment:
      POSTGRES_USER: heuser
      POSTGRES_PASSWORD: hepass  # Change in production!
      POSTGRES_DB: hedb
      # Performance tuning
      POSTGRES_MAX_CONNECTIONS: 200
      POSTGRES_SHARED_BUFFERS: 256MB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations-postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heuser -d hedb"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: he-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # HackerExperience API server
  api:
    build: .
    container_name: he-api
    command: ["sh", "-c", "sqlx migrate run && ./target/release/he-api"]
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=postgresql://heuser:hepass@db:5432/hedb
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=info,he_api=debug
      - JWT_SECRET=change_me_in_production_to_random_string
      - SQLX_OFFLINE=false
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3005/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    profiles:
      - app  # Only start when explicitly requested

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge