global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@hackerexperience.com'
  smtp_require_tls: false

  # Slack webhook URL for notifications
  # slack_api_url: 'YOUR_SLACK_WEBHOOK_URL'

# The root route on which each incoming alert enters.
route:
  # Group alerts by these labels
  group_by: ['alertname', 'cluster', 'service']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 12h

  # Default receiver
  receiver: 'web.hook'

  # Child routes
  routes:
  - match:
      severity: critical
    receiver: critical-receiver
    continue: true

  - match:
      severity: warning
    receiver: warning-receiver
    continue: true

  - match:
      team: security
    receiver: security-receiver

# Inhibition rules allow to mute a set of alerts given that another alert is firing.
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    # Apply inhibition if the alertname is the same.
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'web.hook'
    webhook_configs:
    - url: 'http://localhost:5001/webhook'
      send_resolved: true

  - name: 'critical-receiver'
    email_configs:
    - to: 'oncall@hackerexperience.com'
      headers:
        Subject: '[CRITICAL] HackerExperience Alert: {{ .GroupLabels.alertname }}'
      send_resolved: true
    # slack_configs:
    # - channel: '#critical-alerts'
    #   title: 'Critical Alert'
    #   text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

  - name: 'warning-receiver'
    email_configs:
    - to: 'team@hackerexperience.com'
      headers:
        Subject: '[WARNING] HackerExperience Alert: {{ .GroupLabels.alertname }}'
      send_resolved: true

  - name: 'security-receiver'
    email_configs:
    - to: 'security@hackerexperience.com'
      headers:
        Subject: '[SECURITY] HackerExperience Alert: {{ .GroupLabels.alertname }}'
      send_resolved: true
    webhook_configs:
    - url: 'http://localhost:5002/security-webhook'
      send_resolved: false