[package]
name = "he-leptos-frontend"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "he-leptos-frontend"
path = "src/main.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Leptos framework
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }

# WASM bindings
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
console_error_panic_hook = { workspace = true }

# Shared game mechanics (will be added later when dependencies are resolved)
# he-game-mechanics = { path = "../he-game-mechanics" }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Time and decimal handling
chrono = { workspace = true }
rust_decimal = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Async utilities
futures = { workspace = true }

# HTTP client for API calls (simplified for now)
reqwest = { workspace = true, features = ["json"] }

[features]
default = ["csr"]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]