[package]
name = "he-db"
version = "0.1.0"
edition = "2021"

[dependencies]
he-core = { path = "../he-core" }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "mysql", "chrono", "uuid", "migrate"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }
