[package]
name = "he-helix-id"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
uuid = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }