[package]
name = "he-game-mechanics"
version = "0.1.0"
edition = "2021"
description = "HackerExperience game mechanics engine with all algorithms, formulas, and business rules"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
rust_decimal = { version = "1.0", features = ["serde"] }
rust_decimal_macros = "1.0"

# Internal dependencies
he-core = { path = "../he-core" }

[dev-dependencies]
tokio-test = "0.4"
criterion = "0.5"

[[bench]]
name = "game_mechanics"
harness = false