[package]
name = "he-cron"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-cron-scheduler = "0.10"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "mysql", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
aws-sdk-s3 = "1.0"
aws-config = "1.0"
thiserror = "1.0"
async-trait = "0.1"
rand = "0.8"

# Internal dependencies
he-db = { path = "../he-db" }
he-core = { path = "../he-core" }

[dev-dependencies]
tokio-test = "0.4"

[lib]
name = "he_cron"
path = "src/lib.rs"

[[bin]]
name = "he-cron"
path = "src/bin/he-cron.rs"