apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackerexperience-backend
  namespace: production
  labels:
    app: hackerexperience
    component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hackerexperience
      component: backend
  template:
    metadata:
      labels:
        app: hackerexperience
        component: backend
    spec:
      containers:
      - name: backend
        image: hackerexperience/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hackerexperience-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: hackerexperience-secrets
              key: jwt-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: hackerexperience-secrets
              key: encryption-key
        - name: RUST_LOG
          value: "info,he_api=debug"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackerexperience-frontend
  namespace: production
  labels:
    app: hackerexperience
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hackerexperience
      component: frontend
  template:
    metadata:
      labels:
        app: hackerexperience
        component: frontend
    spec:
      containers:
      - name: frontend
        image: hackerexperience/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hackerexperience-backend
  namespace: production
spec:
  selector:
    app: hackerexperience
    component: backend
  ports:
  - port: 3005
    targetPort: 3005
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: hackerexperience-frontend
  namespace: production
spec:
  selector:
    app: hackerexperience
    component: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackerexperience-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/limit-rps: "50"
spec:
  tls:
  - hosts:
    - hackerexperience.com
    - www.hackerexperience.com
    - api.hackerexperience.com
    secretName: hackerexperience-tls
  rules:
  - host: hackerexperience.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackerexperience-frontend
            port:
              number: 80
  - host: www.hackerexperience.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackerexperience-frontend
            port:
              number: 80
  - host: api.hackerexperience.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackerexperience-backend
            port:
              number: 3005

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hackerexperience-backend-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hackerexperience-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80