use leptos::*;
use crate::components::*;

pub mod control_panel;
pub mod task_manager;
pub mod dashboard;
pub mod processes;
pub mod hardware;
pub mod software;
pub mod internet;
pub mod connections;
pub mod missions;
pub mod logs;
pub mod university;
pub mod finances;
pub mod clan;
pub mod ranking;
pub mod utilities;
pub mod login;
pub mod register;
pub mod profile;
pub mod bank;
pub mod marketplace;
pub mod leaderboard;

pub use control_panel::*;
pub use task_manager::*;
pub use dashboard::*;
pub use processes::*;
pub use hardware::*;
pub use software::*;
pub use internet::*;
pub use connections::*;
pub use missions::*;
pub use logs::*;
pub use university::*;
pub use finances::*;
pub use clan::*;
pub use ranking::*;
pub use utilities::*;
pub use login::*;
pub use register::*;
pub use profile::*;
pub use bank::*;
pub use marketplace::*;
pub use leaderboard::*;